// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomLeftSlot': string;
  'bottomRightSlot': string;
  'fireBrigade': string;
  'map': string;
  'overMap': string;
  'search': string;
  'topLeftSlot': string;
  'topRightSlot': string;
}
export const cssExports: CssExports;
export default cssExports;
