parser: babel-eslint
extends:
    - airbnb
plugins:
    - jest
env:
    browser: true
    jest/globals: true
globals:
    jsdom: false
rules:
    "react/jsx-filename-extension": [1, { "extensions": [".tsx"] }]
    "react/jsx-props-no-spreading": 0
