image: node:13

stages:
  - install
  - bootstrap
#  - test
  - build
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  API: "kcfirebrigade"
  NODE_ENV: "production"

install:
  stage: install
  script:
    - yarn install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 1 day
    paths:
      - .npm/
      - node_modules/

bootstrap:
  stage: bootstrap
  script:
    - yarn install
    - yarn bootstrap
  dependencies:
    - install

#test:
#  stage: test
#  script:
#    - yarn test
#  dependencies:
#    - install

build:
  stage: build
  script:
    - echo $API
    - echo $NODE_ENV
    - yarn build
  dependencies:
    - install
  artifacts:
    paths:
      - k2-dev/base/dist

release:
  stage: release
  script:
    - echo $API
    - echo $NODE_ENV
    - echo $NEXUS_NPM_TOKEN
    - yarn publish
  dependencies:
    - install
