stages:
  - install
  - bootstrap
  - lint
  - test
  - build
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
#  CI_DEBUG_TRACE: "true"

.default-job-settings:
  tags:
    - npm
    - docker

install:
  extends: .default-job-settings
  stage: install
  script:
    - npm ci
  cache:
    paths:
      - node_modules/
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - node_modules/

bootstrap:
  extends: .default-job-settings
  stage: bootstrap
  script:
    - npm run bootstrap
  dependencies:
    - install

lint:
 extends: .default-job-settings
 stage: lint
 variables:
   NODE_ENV: "development"
 script:
   - npm run lint
 dependencies:
   - install

test:
  extends: .default-job-settings
  stage: test
  script:
    - npm run test
  dependencies:
    - install

build:
  extends: .default-job-settings
  stage: build
  variables:
    NODE_ENV: "production"
  script:
    - echo $NODE_ENV
    - npm run build
  dependencies:
    - install
  artifacts:
    paths:
      - k2-dev/base/dist

release:
  extends: .default-job-settings
  stage: release
  script:
    - npm run lerna:publish
  dependencies:
    - install
