image: node:13

stages:
  - install
  - bootstrap
  - test
  - build
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

install:
  stage: install
  script:
    - yarn install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

bootstrap:
  stage: bootstrap
  script:
    - npm bootstrap
  dependencies:
    - install

test:
  stage: test
  script:
    - yarn test
  dependencies:
    - bootstrap

build:
  stage: build
  script:
    - yarn build
  dependencies:
    - bootstrap
    - test

release:
  stage: release
  script:
    - lerna -v
  dependencies:
    - build
