image: node:13

stages:
  - install
  - bootstrap
  - test
  - build
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

install:
  stage: install
  script:
    - yarn install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

bootstrap:
  stage: bootstrap
  script:
    - CI=false yarn run bootstrap
  artifacts:
    paths:
      - k2-dev
      - k2-packages
    expire_in: 60 mins
  dependencies:
    - install

test:
  stage: test
  script:
    - yarn run test
  dependencies:
    - bootstrap

build:
  stage: build
  script:
    - yarn run build
  dependencies:
    - test
