stages:
  - install
  - bootstrap
  - lint
  - test
  # - typecheck
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
#  CI_DEBUG_TRACE: "true"

.default-job-settings:
  tags:
    - npm
    - docker

install:
  extends: .default-job-settings
  stage: install
  script:
    - npm ci
  cache:
    paths:
      - node_modules/
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - node_modules/

bootstrap:
  extends: .default-job-settings
  stage: bootstrap
  script:
    - npm run bootstrap
  dependencies:
    - install

lint:
 extends: .default-job-settings
 stage: lint
 script:
   - npm run lint
 dependencies:
   - install

test:
  extends: .default-job-settings
  stage: test
  script:
    - npm run test
  dependencies:
    - install

# typecheck:
#   extends: .default-job-settings
#   stage: typecheck
#   script:
#     - echo $NODE_ENV
#     - npm run typecheck
#   dependencies:
#     - install

release:
  extends: .default-job-settings
  stage: release
  script:
    - npm run lerna:publish
  dependencies:
    - install
