image: node:13

stages:
  - install
  - bootstrap
  #  - test
  - build
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  API: "kcfirebrigade"

install:
  stage: install
  script:
    - yarn install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

bootstrap:
  stage: bootstrap
  script:
    - yarn bootstrap
  dependencies:
    - install

#test:
#  stage: test
#  script:
#    - yarn test
#  dependencies:
#    - install

build:
  stage: build
  script:
    - echo $API
    - echo $NODE_ENV
    - yarn build
  dependencies:
    - install
  artifacts:
    paths:
      - k2-dev/base/dist

release:
  stage: release
  variables:
    NODE_ENV: "production"
  script:
    - echo $API
    - echo $NODE_ENV
    - lerna publish from-package --yes --regidtry https://nexus.kontur.io/repository/npm-snapshots-a/:_authToken=$NEXUS_NPM_TOKEN
  dependencies:
    - install
