image: node:13

stages:
  - install
  - bootstrap
#  - test
  - build

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

install:
  stage: install
  script:
    - yarn install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .npm/
      - node_modules/

bootstrap:
  stage: bootstrap
  script:
    - yarn bootstrap
  dependencies:
    - install

#test:
#  stage: test
#  script:
#    - yarn test
#  dependencies:
#    - install

build:
  stage: build
  script:
    - yarn build
  dependencies:
    - install

#release:
#  stage: release
#  script:
#    - lerna -v
#  dependencies:
#    - install
