stages:
  - prepare
  - publish

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

.default-job-settings:
  tags:
    - npm
    - docker

prepare:
  extends: .default-job-settings
  stage: prepare
  script:
    - n install 16
    - lerna bootstrap
    - npm run auto:lint
    - npm run build
    - npm run test

  cache:
    paths:
      - node_modules/
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - node_modules/


publish:
  extends: .default-job-settings
  stage: publish
  script:
    - npm run auto:lerna:publish
  dependencies:
    - prepare