## gitlb ci configuration
---
image: node:latest

cache:
  paths:
    - noode_modules/

.default-job-settings:
  tags:
    - yarn
    - node

stages:
  - bootstrap
  - build
  - verify
  - release

bootstrap:
  extends: .default-job-settings
  stage: bootstrap
  script: yarn bootstrap

build:
  extends: .default-job-settings
  stage: build
  script: yarn build

verify:
  extends: .default-job-settings
  stage: verify
  script: yarn test

release:
  extends: .default-job-settings
  stage: release
  script:
    - lerna -v
