version: "3"

services:
  nginx:
    build:
      context: proxy
      dockerfile: Dockerfile
    image: proxy:latest
    container_name: "nginx"
    links:
      - k2-apps-base
      - k2-apps-base1
      - k2-mock-tool
    depends_on:
      - k2-apps-base
      - k2-apps-base1
      - k2-mock-tool
    ports:
      - 9000:9000
    expose:
      - 9000

  k2-mock-tool:
    image: k2-mock-tool
    container_name: "k2-mock-tool"
    build:
      context: mock
      dockerfile: Dockerfile
    command: npm run mock
    ports:
    - 5000:5000
    expose:
    - 5000

  k2-apps-base:
    image: k2-workspace:latest
    container_name: "k2-apps-base"
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn run start
    volumes:
    - ./node_modules:/app/node_modules:cached
    - ./k2-apps/base:/app/k2-apps/base
    - ./k2-packages:/app/k2-packages
#    env_file:
#    - .env
    ports:
    - 8001:8001
    expose:
    - 8001

  k2-apps-base1:
    image: k2-workspace:latest
    container_name: "k2-apps-base1"
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn run start
    volumes:
    - ./node_modules:/app/node_modules:cached
    - ./k2-apps/base1:/app/k2-apps/base1
    - ./k2-packages:/app/k2-packages
    #    env_file:
    #    - .env
    ports:
    - 8002:8002
    expose:
    - 8002
