// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Map': string;
  'activeLink': string;
  'inputs': string;
  'navigation': string;
}
export const cssExports: CssExports;
export default cssExports;
