export const DROPDOWN_ITEM_CLEAR_SELECTION_INDEX = 'CLEAR_SELECTION_INDEX';
export const DROPDOWN_ITEM_CLICK_MENU_ITEM = 'CLICK_MENU_ITEM';
export const DROPDOWN_ITEM_CLOSE_MENU = 'CLOSE_MENU';
export const DROPDOWN_ITEM_OPEN_MENU_AT_FIRST_ITEM = 'OPEN_MENU_AT_FIRST_ITEM';
export const DROPDOWN_ITEM_OPEN_MENU_AT_INDEX = 'OPEN_MENU_AT_INDEX';
export const DROPDOWN_ITEM_OPEN_MENU_CLEARED = 'OPEN_MENU_CLEARED';
export const DROPDOWN_ITEM_SEARCH_FOR_ITEM = 'SEARCH_FOR_ITEM';
export const DROPDOWN_ITEM_SELECT_ITEM_AT_INDEX = 'SELECT_ITEM_AT_INDEX';
export const DROPDOWN_ITEM_SET_BUTTON_ID = 'SET_BUTTON_ID';

export const DROPDOWN_DISABLE_TOOLTIPS = '__UIKIT_DROPDOWN_DISABLE_TOOLTIPS';
