// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'error': string;
  'focus': string;
  'icons': string;
  'inputBox': string;
  'message': string;
  'root': string;
  'successes': string;
}
export const cssExports: CssExports;
export default cssExports;
