// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'checkbox': string;
  'contact': string;
  'contactBtn': string;
  'contacts': string;
  'delimiter': string;
  'header': string;
  'label': string;
  'rootList': string;
  'subtitle': string;
  'title': string;
  'units': string;
}
export const cssExports: CssExports;
export default cssExports;
