name: Lint, Build, Test, Publish
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages, build, test
        run: |
          npm ci
          npm i lerna@4.0.0 -g
          lerna bootstrap
          npm run auto:lint
          npm run build
          npm run test

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref }}
          regex: '^v[0-9]+$'

      - name: Publish package to NPM
        if: ${{ steps.regex-match.outputs.match != '' }} && github.event_name == 'push'
        run: |
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> .npmrc
          npm run auto:lerna:publish
