on:
  push:
  pull_request:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install packages, build, test
        run: |
          npm install
          # npm i lerna -g
          # lerna bootstrap
          # npm run auto:lint
          # npm run build
          # npm run test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish package to NPM
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   run: npm run auto:lerna:publish
